name: Dev-CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-20.04 
    env:
      working-directory: WableServer

    steps: 
    - name: 체크아웃
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '17'

    - name: application.yaml 생성
      run: | 
          echo "${{ secrets.APPLICATION }}" > src/main/resources/application.yaml
      working-directory: ${{ env.working-directory }}

    - name: fire-base.json 생성
      run: | 
          echo "${{ secrets.FIRE_BASE_DEV }}" > src/main/resources/fire-base.json
      working-directory: ${{ env.working-directory }}

    - name: 빌드
      run: |
          chmod +x gradlew
          ./gradlew build -x test
      working-directory: ${{ env.working-directory }}
      shell: bash
